
namespace Phrazer
{
    class SubsNewLineDetector
    {

        bool harvesterMode = false;

        public SubsNewLineDetector(bool hM)
        {
            harvesterMode = hM;
        }
        

        public bool ShouldCreateNewRow(string textBuffer, string word)
        {
            // Experimantal end of phrase recognition feature
            if(
                EndOfPhraseDetected(textBuffer, word)
                // SOME IMPORTANT EXCEPTIONS
                && !textBuffer.EndsWith("Mr.")
                && !textBuffer.EndsWith("MR.")
                && !textBuffer.EndsWith("mr.")
                && !textBuffer.EndsWith("Mrs.")
                && !textBuffer.EndsWith("Dr.")
                && !textBuffer.EndsWith("dr.")
                && !textBuffer.EndsWith("U.S.")
                && !textBuffer.EndsWith("u.s.")
                && !textBuffer.EndsWith("L.A.")
                && !textBuffer.EndsWith("K.O.")
                && !textBuffer.EndsWith("C.E.O.")
                && !textBuffer.EndsWith("a.m.")
                && !textBuffer.EndsWith("p.m.")
                && textBuffer.Length > 2
            ) return true;

            return false;
        }

        bool EndOfPhraseDetected(string textBuffer, string word)
        {
            if(textBuffer.EndsWith(".") 
            || textBuffer.EndsWith("?") 
            || textBuffer.EndsWith("!")
            || textBuffer.EndsWith(")")
            || textBuffer.EndsWith("]")
            || textBuffer.EndsWith("--")
            || textBuffer.EndsWith("...")
            || textBuffer.EndsWith("♪") 
            ) return true;



            // Legacy Mode: Used for poorly formed subtitles (i.e. autogenerated)
            if(
                /* StartingWordDetected */
                word.Trim() == "Why"
                || word.Trim() == "What"
                || word.Trim() == "What's"
                || word.Trim() == "We're"
                || word.Trim() == "The"
                || word.Trim() == "Then"
                || word.Trim() == "There"
                || word.Trim() == "To"
                || word.Trim() == "In"
                || word.Trim() == "So"
                || word.Trim() == "Perhaps"
            ) return true;
            

            if(
                harvesterMode &&
                (  textBuffer.StartsWith("Trust me,")
                || textBuffer.StartsWith("trust me,")
                || textBuffer.StartsWith("By the way,")
                || textBuffer.StartsWith("by the way,")
                || textBuffer.StartsWith("I'm sorry,")
                || textBuffer.StartsWith("I don't know,")
                || textBuffer.StartsWith("You know,")
                || textBuffer.StartsWith("All right,")
                || textBuffer.StartsWith("No big deal,")
                )
            ) return true;

            return false;   
        }

        
    }
}
